name: Deploy Microservice to VPS

on:
  push:
    branches:
      - update-vps # Or your deploy branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    environment: secrets
    steps:
      - name: Multiple commands
        uses: appleboy/ssh-action@v1
        with:
          host: microservices.appf4.io.vn
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            whoami
            ls -al
