name: Deploy Microservice to VPS

on:
  push:
    branches:
      - update-vps # Or your deploy branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    environment: secrets
    steps:
      - name: Multiple commands
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            cd /root/f4-microserices-vps-configuration/Spring_AdamStore

            if [ $? -ne 0 ]; then
              echo "Error: Directory does not exist or cannot be accessed."
              exit 1
            fi

            echo "Pulling latest changes..."
            git pull

            echo "Running docker-compose up..."
            docker compose up -d --build

            echo "Deployment script finished."
