name: Deploy Microservice to VPS

on:
  push:
    branches:
      - update-vps  # Or your deploy branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H microservices.appf4.io.vn >> ~/.ssh/known_hosts
        shell: bash

      - name: SSH into VPS and deploy
        run: |
          ssh -o StrictHostKeyChecking=no root@microservices.appf4.io.vn << 'EOF'
            echo '✅ Connected to VPS'

            # 🔄 Pull latest changes
            cd /root/your-app-folder
            git pull origin update-vps

            # ♻️ Restart service
            docker compose down
            docker compose up -d --build

            echo '🚀 Deployment done!'
          EOF
